### ISSUE TITLE
App crashes when going into character detail page

### ISSUE THREAD

**Issue by YoungMaker** [YoungMaker/iORC#80] opened 2018-03-20 23:42 UTC
Due to null pointer exception:  `Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference`

**Comment by hwilling** [comment] 2018-03-21 00:08
Fixed issue in 825e051. Problem was being caused by the view Ids not being set before having values assigned to those ids.

**Closed by hwilling** 2018-03-21 00:08 UTC
Labels: High Priority, In Progress, bug
